\LoadClass[12pt,a4paper]{scrartcl}	
\ProvidesClass{praktikum}

% Packages
\usepackage[ngerman]{babel}
\usepackage[utf8]{inputenc}
\usepackage{cmap}
\usepackage{amsmath}
\usepackage{amsthm}		
\usepackage{amssymb}
\usepackage{booktabs}
\usepackage{fancyhdr}
\usepackage{setspace}
\usepackage{subfigure}
\usepackage{siunitx}

% Headings
\pagestyle{fancy}
\fancyhf{}
\fancyhead[L]{\nameeins, \namezwei}
\fancyhead[R]{\versuchsname}
\fancyfoot[C]{\thepage}
